### PR TITLE
Upgrade DepMap to 22Q2

### PR DESCRIPTION
**Pull request by jrouly**
# Proposed Changes

Upgrades DepMap release from 21Q4 to 22Q2.

Going to the next release (current latest) 22Q4 involves breaking schema changes that I do not yet understand how to incorporate.

### CODE REVIEW

**Comment by jrouly** [comment]
I've tested this by issuing `cancer_data.download()` invocations for each of the updated rows and verified that they succeed and checksums match.

**Comment by jrouly** [comment]
After using this module to regenerate the DepMap H5 file and pulling that into downstream Zephyr, I'm seeing these dimensions:

```python
>>> for attr in dir(depmap):
...     if isinstance(getattr(depmap, attr), pd.DataFrame):
...         print(attr, getattr(depmap, attr).shape)
annotations (1840, 30)
copy_number (1766, 25368)
crispr (1086, 17386)
crispr_common_essentials (1912, 2)
expression (1389, 19177)
mutations_hotspot (1771, 19131)
prism_annotations (12230, 6)
prism_eff (568, 4518)
rnai_achilles (501, 16755)
rnai_combined (711, 17309)
rnai_drive (397, 7975)
```

**Comment by jrouly** [comment]
Using the old DepMap H5 file results in these dimensions:

```python
>>> zdata = ZephyrData(s3=s3, bucket="zephyr-workloads-staging-data", s3_prefix="zephyr-data/")
>>> depmap = zdata.load_depmap()
>>> for attr in dir(depmap):
...     if isinstance(getattr(depmap, attr), pd.DataFrame):
...         print(attr, getattr(depmap, attr).shape)
annotations (1811, 27)
copy_number (1740, 27562)
crispr (1032, 17393)
crispr_common_essentials (1869, 2)
expression (1376, 19177)
mutations_hotspot (1747, 19144)
prism_annotations (12230, 6)
prism_eff (568, 4518)
rnai_achilles (501, 16755)
rnai_combined (711, 17309)
rnai_drive (397, 7975)
```

**Comment by jrouly** [comment]
And testing with DepMap V2:

```python
>>> overrides = {
...     ZephyrData.ccle_expression.name: "depmap/22Q2/CCLE_expression.csv",
...     ZephyrData.ccle_mutations.name: "depmap/22Q2/CCLE_mutations.csv",
...     ZephyrData.crispr_gene_effect.name: "depmap/22Q2/CRISPR_gene_effect.csv",
...     ZephyrData.depmap_annotations.name: "depmap/22Q2/sample_info.csv",
... }
>>> zdata = ZephyrData(
...     dataset_file_overrides=overrides,
...     s3=s3,
...     bucket="zephyr-workloads-staging-data",
...     s3_prefix="zephyr-data/",
... )
>>> depmap = zdata.load_depmap_v2()
>>> for attr in dir(depmap):
...     if isinstance(getattr(depmap, attr), pd.DataFrame):
...         print(attr, getattr(depmap, attr).shape)
copy_number (1060, 763)
crispr (1086, 17387)
expression (1406, 19222)
mutations (1235466, 32)
```

**Comment by jrouly** [comment]
compared to the 22Q1 data:

```python
>>> zdata = ZephyrData(s3=s3, bucket="zephyr-workloads-staging-data", s3_prefix="zephyr-data/")
>>> depmap = zdata.load_depmap_v2()
>>> for attr in dir(depmap):
...     if isinstance(getattr(depmap, attr), pd.DataFrame):
...         print(attr, getattr(depmap, attr).shape)
copy_number (1060, 763)
crispr (1054, 17387)
expression (1389, 19178)
mutations (1230245, 32)
```

**Review by MaayanBaron — APPROVED** [review]

**Pull request merged**
